### ISSUE TITLE
Possible issue with multiple CoC codes

### ISSUE THREAD

**Issue by rokeya2023** [HUD-Data-Lab/DataLab#7] opened 2022-12-20 16:59 UTC
On Page # 5 in Programming Specification, the steps number 5 indicates the condition for projects with multiple CoC Codes with filtering instructions. Please refer to line # 47 to line #50 in R Studio. Programming specification should apply here.
Screenshot for the MultiCoC codes in R studio:
![image](https://user-images.githubusercontent.com/120743917/208766792-98563248-742b-4dc7-864a-7a2a78ecd299.png)

Please refer to line number 59, where Filter enrolment by the client location(element 3.16)  logic which does not comply the condition. This only applies when Multiple CoC. The logic is correct but only applies to Multiple CoC.
![image](https://user-images.githubusercontent.com/120743917/208766902-65a144ac-f542-4027-bfbd-707dc410e2e4.png)
Screenshot for the Programming Spec:
![image](https://user-images.githubusercontent.com/120743917/208766975-f2171ffb-ff30-445a-8c30-46678fa0c47c.png)

**Comment by HUD-Data-Lab** [comment] 2022-12-21 05:45
Duplicate of #2 

Resolved by ab0c161d5a7688f8bc6169e7698b0d9cabd146de

**Closed by HUD-Data-Lab** 2022-12-21 05:45 UTC
Labels: bug, duplicate
